spring:
  profiles:
    active: dev
  #main: #解决包冲突
    #allow-bean-definition-overriding: true
server:
  port: 8002

mybatis-plus:
  mapper-locations: classpath*:/mappers/**/*.xml
  type-aliases-package: com.cql.**.entity


dog:
  name: cql
