spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.49.119:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 1q2w3e4R!@

  data:
    elasticsearch:
        repositories:
          enabled: true
        cluster-name: myEs
        cluster-nodes: 127.0.0.1:9300
        #cluster-nodes: hadoop137:9300,hadoop138:9300,hadoop139:9300

dog:
  name: cql

#elasticsearch:
#  host: 127.0.0.1
#  port: 9200


